flags: {}
packages:
- '.'
extra-deps:
- event-list-0.1.1.2
- midi-0.2.1.5
- non-negative-0.1.1
- utility-ht-0.0.10
- explicit-exception-0.1.7.3
- monoid-transformer-0.0.3
resolver: nightly-2015-07-26
